wultra/powerauth-cmd-tool

- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/VerifyTokenStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/model/VerifyTokenStepModel.java
- powerauth-java-cmd/src/main/java/io/getlime/security/powerauth/app/cmd/Application.java
Added a new 'validate token' method
> Fix #7: Implement support for the new token based authentication

- pom.xml
- powerauth-java-cmd-lib/pom.xml
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/VaultUnlockStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/model/VaultUnlockStepModel.java
- powerauth-java-cmd/pom.xml
- powerauth-java-cmd/src/main/java/io/getlime/security/powerauth/app/cmd/Application.java
Updated version and dependency versions where required
> Fix #12: Add reason for vault unlock

- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/CreateActivationStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/CreateTokenStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/GetStatusStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/PrepareActivationStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/RemoveStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/VaultUnlockStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/VerifySignatureStep.java
Changes in this pull request:
- Fix #47: Crypto 3.0: Tokens
- PowerAuth protocol version separation
- Fixed typo in httpAuthorizationHeader
> V3 tokens using new ECIES and version separation

- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/CreateTokenStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/RemoveStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/VaultUnlockStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/VerifySignatureStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/util/ConfigurationUtils.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/util/CounterUtil.java
I isolated changes of the hash based counter to this pull request in powerauth-cmd-tool.
There will be a conflict with PR https://github.com/wultra/powerauth-cmd-tool/pull/57 because the versioning of steps is moved to classes for tokens, however resolving the conflict should be easy.
> Fix #44: Crypto 3.0: Hash based counter

- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/PrepareActivationStep.java
Unification of variable names
Fixed typo in signatureKnowledgeSecretKey
> Fix #63: Crypto 3.0: Update activation layer 1 response

- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v2/VaultUnlockStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/CreateTokenStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/VaultUnlockStep.java
- powerauth-java-cmd/src/main/java/io/getlime/security/powerauth/app/cmd/Application.java
Changes in this PR:
- Fix #46: Crypto 3.0: Vault unlock
- Updated incrementing of counter for version 2.0
- Fixed invalid lowercase http method in signature base String
> Fix #46: Crypto 3.0: Vault unlock

- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v2/CreateActivationStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v2/PrepareActivationStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/PrepareActivationStep.java
Updated logic for calculation of activation fingerprint.
> Fix #79: Crypto 3.0: Update fingerprint for activations

- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v2/CreateActivationStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v2/PrepareActivationStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/CreateActivationStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/PrepareActivationStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/util/CounterUtil.java
- powerauth-java-cmd/src/main/java/io/getlime/security/powerauth/app/cmd/Application.java
This pull request introduces custom activations in cmd-tools with several minor improvements:
- Fix #56: Crypto 3.0: Custom activation
- Fixed typo in knowledge key variable name
- Added logging for create activation step
- Fixed null value handling for counter
> Fix #56: Crypto 3.0: Custom activation

- docs/Home.md
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/model/RemoveTokenStepModel.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v2/RemoveTokenStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/RemoveTokenStep.java
- powerauth-java-cmd/src/main/java/io/getlime/security/powerauth/app/cmd/Application.java
Implementation of RemoveToken step.
> Fix #98: Implement RemoveToken step

- pom.xml
- powerauth-java-cmd-lib/pom.xml
- powerauth-java-cmd/pom.xml
This pull request contains following changes:
- Update version to 0.22.0
- Spring boot dependency updated to 2.1.2.RELEASE
- Updated BC dependency
> Fix #101: Update version and dependencies

- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/model/ActivationRecoveryStepModel.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/model/ConfirmRecoveryCodeStepModel.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/ActivationRecoveryStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/ConfirmRecoveryCodeStep.java
- powerauth-java-cmd/src/main/java/io/getlime/security/powerauth/app/cmd/Application.java
This pull request contains implementation of activation via recovery code and confirmation of recovery codes.
> Fix #104: Implement support for recovery codes

- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/util/ConfigurationUtil.java
I removed the hardcoded values.
> Fix #133: Fix issues found by coverity scan

- pom.xml
- powerauth-java-cmd-lib/pom.xml
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/VerifySignatureStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v2/CreateActivationStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v2/CreateTokenStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v2/GetStatusStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v2/PrepareActivationStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v2/RemoveStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v2/RemoveTokenStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v2/VaultUnlockStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/ActivationRecoveryStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/CommitUpgradeStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/ConfirmRecoveryCodeStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/CreateActivationStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/CreateTokenStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/EncryptStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/GetStatusStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/PrepareActivationStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/RemoveStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/RemoveTokenStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/SignAndEncryptStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/StartUpgradeStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/VaultUnlockStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/util/ConfigurationUtil.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/util/EncryptedStorageUtil.java
- powerauth-java-cmd/pom.xml
- powerauth-java-cmd/src/main/java/io/getlime/security/powerauth/app/cmd/Application.java
- powerauth-java-cmd/src/test/java/io/getlime/security/powerauth/app/cmd/ApplicationTest.java
This pull request removes the crypto provider abstraction and updates the version to `0.24.0-SNAPSHOT`.
> Fix #138: Deprecate crypto provider abstraction

- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/VerifySignatureStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/VerifyTokenStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v2/CreateActivationStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v2/CreateTokenStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v2/EncryptStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v2/GetStatusStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v2/PrepareActivationStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v2/RemoveStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v2/RemoveTokenStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v2/VaultUnlockStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/ActivationRecoveryStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/CommitUpgradeStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/ConfirmRecoveryCodeStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/CreateActivationStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/CreateTokenStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/EncryptStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/GetStatusStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/PrepareActivationStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/RemoveStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/RemoveTokenStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/SignAndEncryptStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/StartUpgradeStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/VaultUnlockStep.java
The change reflects added `queryParams`.
> Update REST client calls

- pom.xml
- powerauth-java-cmd-lib/pom.xml
- powerauth-java-cmd/pom.xml
Fix #199: Update powerauth-restful-model to 1.1.0 when available
> Fix #198: Update version to 1.1.0

- docs/Readme.md
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/consts/PowerAuthStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/header/PowerAuthHeaderFactory.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/header/TokenAndEncryptionHeaderProvider.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/AbstractBaseStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/model/TokenAndEncryptStepModel.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/model/data/TokenAndEncryptionHeaderData.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/EncryptStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/SignAndEncryptStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/TokenAndEncryptStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/util/EncryptionUtil.java
- powerauth-java-cmd/src/main/java/io/getlime/security/powerauth/app/cmd/Application.java
A new step for combined encryption and token authentication.
> Fix #234: Add token-encrypt step

- .github/workflows/maven-deploy.yml
- .github/workflows/maven-test.yml
- pom.xml
- powerauth-java-cmd/pom.xml
new reusable workflows part of wultra/tasklist/issues/23
> new reusable workflows part of wultra/tasklist#23

- pom.xml
- powerauth-java-cmd-lib/pom.xml
- powerauth-java-cmd/pom.xml
> Stop using revision property for project version

- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/logging/model/StepRequest.java
Issue #303
Refactor at #304 was too heavy.
> Revert logic at StepRequest#requestObject()

- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/consts/PowerAuthVersion.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/AbstractActivationStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/AbstractBaseStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/context/security/ActivationSecurityContext.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/context/security/SimpleSecurityContext.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/model/data/ActivationData.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/ActivationRecoveryStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/ConfirmRecoveryCodeStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/CreateActivationStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/CreateTokenStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/EncryptStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/PrepareActivationStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/SignAndEncryptStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/StartUpgradeStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/TokenAndEncryptStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/VaultUnlockStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/util/EncryptionUtil.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/util/SecurityUtil.java
This pull request introduces updated ECIES implementation for crypto 3.2.
> Update ECIES implementation for crypto 3.2

- .github/workflows/codeql-analysis.yml
> Fix #326: Add CodeQL Analysis

- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/ComputeOfflineSignatureStep.java
(cherry picked from commit 1b6a28d892c86bb364b9aec8dd2f49876e6d3180)
> Fix #372: Edit data parsing in offline signature calculation (#373)

- powerauth-java-cmd-lib/src/main/java/com/wultra/security/powerauth/lib/cmd/steps/GetStatusStep.java
- powerauth-java-cmd-lib/src/main/java/com/wultra/security/powerauth/lib/cmd/steps/base/AbstractActivationStep.java
- powerauth-java-cmd-lib/src/main/java/com/wultra/security/powerauth/lib/cmd/steps/base/AbstractBaseStep.java
- powerauth-java-cmd-lib/src/main/java/com/wultra/security/powerauth/lib/cmd/steps/model/GetStatusStepModel.java
- powerauth-java-cmd-lib/src/main/java/com/wultra/security/powerauth/lib/cmd/steps/pojo/ResultStatusObject.java
- powerauth-java-cmd/src/main/java/com/wultra/security/powerauth/app/cmd/Application.java
This pull request updates the status step in PowerAuth Command-Line Tool to correctly parse and display activation status information for crypto4, fix of #500.
> Fix #500: Update activation status step

- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/EncryptStep.java
- powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/util/TemporaryKeyUtil.java
* Fix #525: Coverity - Possible NPE
(cherry picked from commit 542c0a25c26881b04f6cf4c3270509663646ab74)
> Fix #525: Coverity - Possible NPE (#526)

- pom.xml
(cherry picked from commit 4006fe6265782254d1590f79c70854511ffa34a9)
> Fix #530: Bump Spring Boot to 3.4.6
